name: Publish to Global PyPI

on:
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x" # Set the Python version you need

            - name: Install build tools
              run: |
                  python -m pip install --upgrade pip
                  pip install setuptools wheel twine

            - name: Build the package
              run: |
                  python setup.py sdist bdist_wheel

            - name: Publish package to Global PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.GLOBAL_PYPI_API_TOKEN }}
              run: |
                  twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
